### ISSUE TITLE
Query Execution

### ISSUE THREAD

**Issue by r4sk01** [hkbudb/vchain-plus#3]
Hello,

I am trying to execute the query:
`
./target/release/query -e -n -k ~/Documents/vChain/vchain-plus/generatedKey -i ~/Documents/vChain/vchain-plus/output/db -q ~/Documents/vChain/vchain-plus/queryList/queryTwo.json -r ~/Documents/vChain/vchain-plus/result/process_time.json
`

I am getting the following error:
`
Error: invalid type: map, expected a sequence at line 1 column 0
`
My `queryTwo.json`:
`{
    "start_blk": 1,
    "end_blk": 10,
    "range": [
      [
        1,
        3
      ],
      [
        6,
        6
      ]
    ],
    "keyword_exp": {
      "and": [
        {
          "input": "'a'"
        },
        {
          "input": "'b'"
        }
      ]
    }
}
`
What does that map error means?

**Comment by haixin-wang** [comment]
This error is related to the deserialization of json format. Please try to modify your queryTwo.json as follows:
[
    {
        "start_blk": 1,
        "end_blk": 10,
        "range": [
            [
                1, 
                3
            ], 
            [
                6,
                6
            ]
        ],
        "keyword_exp": {
            "and": [
                {
                    "input": "a"
                },
                {
                    "input": "b"
                }
            ]
        }
    }
]

Hope this helps.

**Comment by haixin-wang** [comment]
This error is related to the deserialization of json format. Please try to modify your queryTwo.json as follows:
```json
[ { "start_blk": 1, "end_blk": 10, "range": [ [ 1, 3 ], [ 6, 6 ] ], "keyword_exp": { "and": [ { "input": "a" }, { "input": "b" } ] } } ]
```

Hope this helps.

**Comment by HuLinNie** [comment]
./build_chain -t 2 -t 4 -t 8 -t 16 -t 32 --id-fanout 4 -b 4 -m 4095 -d 1 -k ~/workspace/vchain-plus-master/vchain-plus-master/target/release/pk -i ~/workspace/vchain-plus-master/vchain-plus-master/target/release/dataset.dat -r ~/workspace/vchain-plus-master/vchain-plus-master/target/release/res/build_time.json -o ~/workspace/vchain-plus-master/vchain-plus-master/target/release/output/db
Error: No such file or directory (os error 2)

How to slove this question?
