### ISSUE TITLE
Missing Query Results

### ISSUE THREAD

**Issue by ernman37** [hkbudb/vchain-plus#4]
# Missing Query Results

## Background 

- Using key size: `128` 
- Data: 
  - [rand-tpch10-1.txt](https://github.com/hkbudb/vchain-plus/files/11056316/rand-tpch10-1.txt)
  - The data that we are using follows that for each numerical value ie [ 1 ] has 7 corresponding values in the block ie 
```
1 [ 1 ] { 1 }
1 [ 1 ] { 2 }
1 [ 1 ] { 3 }
1 [ 1 ] { 4 }
1 [ 1 ] { 5 }
1 [ 1 ] { 6 }
1 [ 1 ] { 7 }
```
  - Each block can contain multiple differnt numerical values and each numerical value must not be repeated in any other block ie
```
1 [ 1 ] { 1 }
...
1 [ 1 ] { 7 }
1 [ 2 ] { 1 }
...
1 [ 2 ] { 7 }
1 [ 3 ] { 1 }
...
1 [ 5 ] { 7 }
2 [ 6 ] { 1 }
2 [ 6 ] { 2 }
2 [ 6 ] { 3 }
2 [ 6 ] { 4 }
2 [ 6 ] { 5 }
2 [ 6 ] { 6 }
2 [ 6 ] { 7 }
```
- Block generation command: 
  - `../vchain-plus/target/release/build_chain -t 2 -t 4 -t 8 -t 16 -t 32 --id-fanout 4 -b 4 -d 1 -m 127 -k keys/128 -r rand-tpch10-1.txt.json -i ../data/1/rand-tpch10-1.txt -o blocks/128/1/rand-tpch10-1.txt`
  - Updated `query.rs` to output results with
```
info!("Results: ");
for(objs, _) in &results {
     info!("{:#?}", objs);
}
```

## Issue 1

When running with a query such as:
```
{ 
        "start_blk": 1, 
        "end_blk": 1, 
        "range": [ 
          [ 1, 1 ] 
        ]
}
```

It produces the correct results and returns the data from the following lines:

```
1 [ 1 ] { 4 }
1 [ 1 ] { 7 }
1 [ 1 ] { 3 }
1 [ 1 ] { 1 }
1 [ 1 ] { 6 }
1 [ 1 ] { 2 }
1 [ 1 ] { 5 }
``` 

When run with an extended end block such as:

```
{ 
        "start_blk": 1, 
        "end_blk": 10, 
        "range": [ 
          [ 1, 1 ] 
        ]
}
```

It incorrectly returns only one line corresponding to:
 
```
1 [ 1 ] { 5 }
```

This can be replicated with any end block #. (other than 1 in this example) 

## Issue 2

This is a similar issue, when running a query like: 

```
{ 
        "start_blk": 1, 
        "end_blk": 9, 
        "range": [ 
          [ 1, 9 ] 
        ]
}
```

It correctly returns data from blocks 1-9 totaling 63 lines. 

but when the same query is run with a larger data set such as 
[rand-tpch10-5-3.txt](https://github.com/hkbudb/vchain-plus/files/11056734/rand-tpch10-5-3.txt)

It produces the incorrect results and only returns 57 lines from the expected 315 lines. 

Returning to the original set...

when running a query over all the data such as: 

```
{ 
        "start_blk": 1, 
        "end_blk": 10, 
        "range": [ 
          [ 1, 10 ] 
        ]
    }
```

It incorrectly returns 64 lines missing 6 lines that would be expected to be in the query results. 

The size lines it misses happen to be the first 6 lines of the data file as well: 

```
1 [ 1 ] { 4 }
1 [ 1 ] { 7 }
1 [ 1 ] { 3 }
1 [ 1 ] { 1 }
1 [ 1 ] { 6 }
1 [ 1 ] { 2 }
```
With larger data sets such as the 1 provided above the only way it succesfullly returns the intended result is giving it a single start and end block and a numerical range that is contained only within that single block, any increase to the end block causes incorrect input, and any extension of the numerical range + end block causes incorrect output as well. 

## Further Information

- These errors can all be replicated on a larger key size (currently I have run with 128, 1024, 2048 and 4096)
- These erros can all be replicated with larger block sizes (currently I have chains built for 10, 100, 1000, 100,000, 500,000, 1,000,000 using key sizes 2048 and 4096) 
- These errors can all be replicated with blocks containing more numerical data values ie ranges 1-3, 1-5
- I have tried to hardcode a keyword expression range for values "1"-"7" using multiple nested `or` statements but it produced the same results as shown above

**Comment by haixin-wang** [comment]
The missing result is caused by large block size (n) and maximum sliding window size (k). The key size should be no less than (2k-1)*m, which is clarified in the paper. This design is to limit the public key size as well as avoid collisions and you may refer to the paper for more details. In the aforementioned cases, it seems you use large block size and small public keys size. Please either reduce the block size or increase the public key size.
